version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/images/workstation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/guide"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/lab-setup"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
