services:
  workstation:
    extends:
      file: ../docker-compose.yml
      service: workstation

  guide:
    extends:
      file: ../docker-compose.yml
      service: guide

  pypi-private:
    extends:
      file: ../docker-compose.yml
      service: pypi-private

  pypi-public:
    extends:
      file: ../docker-compose.yml
      service: pypi-public

  verdaccio:
    extends:
      file: ../docker-compose.yml
      service: verdaccio

  gitea:
    extends:
      file: ../docker-compose.yml
      service: gitea

  registry:
    extends:
      file: ../docker-compose.yml
      service: registry

  lab-setup:
    extends:
      file: ../docker-compose.yml
      service: lab-setup

volumes:
  pypi-private-data:
  pypi-public-data:
  verdaccio-data:
  gitea-data:
  registry-data:
