apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics-aggregator
  labels:
    app: metrics-aggregator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app: metrics-aggregator
